### PR TITLE
Formal BBox struct

### LINKED ISSUE #375: Issue with parsing bbox coords in elevation code
While working on #374 , I found this issue in the elevation code:

https://github.com/louis-e/arnis/blob/a969d65ae4ab55717a32f2c9c1bf666452e374d6/src/ground.rs#L130-L133

Here, `split_whitespace` is the wrong method to call. In CLI mode, it fails, leading the elevation code to be skipped.

Does the GUI pass the bbox coords in with space delimiters? The CLI breaks unless you use comma delimiters.

We should settle on one way to do this, or even better, replace the bbox string with an actual struct so we don't have to parse it in worldgen logic.

### PR DESCRIPTION
**Pull request by benjamin051000**
We need a more standardized way to represent bounding boxes, as we kind of just throw the string around and parse it into the four corresponding values when we need to.

Fixes #375 

# To Do
- [x] Get GUI working with this 
- [x] Fix compile errors
- [x] Fix render bug

### CODE REVIEW

**Comment by benjamin051000** [comment]
Blocked on #378

**Comment by benjamin051000** [comment]
Okay, on my local machine, I've definitely swapped a lat/lng somewhere... because renders are no longer working :( I'll try to figure out which

File: src/bbox.rs [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+            });
+        }
+
+        Err("Invalid BBox".to_string())
+    }
+
+    pub fn from_str(s: &str) -> Result<Self, String> {
+        let [min_lat, min_lng, max_lat, max_lng]: [f64; 4] = s
+            .split(',')
+            .map(|e| e.parse().unwrap())
```
Comment (benjamin051000) [inline src/bbox.rs:30]: Should this return an `Err` signifying parsing failure?

File: src/bbox.rs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+            .collect::<Vec<_>>()
+            .try_into()
+            .unwrap();
```
Comment (benjamin051000) [inline src/bbox.rs:33]: Should this return an `Err`? What cases will the `try_into` fail?

File: src/main.rs [hunk 3]
```diff
@@ -401,26 +392,13 @@ fn gui_start_generation(
...
     terrain_enabled: bool,
 ) -> Result<(), String> {
+    use bbox::BBox;
+
     tauri::async_runtime::spawn(async move {
         if let Err(e) = tokio::task::spawn_blocking(move || {
-            // Utility function to reorder bounding box coordinates
-            fn reorder_bbox(bbox: &[f64]) -> (f64, f64, f64, f64) {
-                (bbox[1], bbox[0], bbox[3], bbox[2])
-            }
```
Comment (benjamin051000) [inline src/main.rs:414]: hm, do I still need to do this? Maybe we can just make the GUI return it in the right order in the first place...

File: src/retrieve_data.rs [hunk 4]
```diff
@@ -130,7 +131,10 @@ pub fn fetch_data(
     .relsinbbox out body;
     .waysinbbox out body;
     .nodesinbbox out skel qt;"#,
-        bbox.1, bbox.0, bbox.3, bbox.2
+        bbox.min().lng,
+        bbox.min().lat,
+        bbox.max().lng,
+        bbox.max().lat
```
Comment (benjamin051000) [inline src/retrieve_data.rs]: I'm not rendering buildings anymore... It's gotta be this that's causing the issue.

Comment (benjamin051000) [reply src/retrieve_data.rs]: Okay, I might be wrong, because when I switch these around, the API doesn't return any data. I guess I'm stumped as to why this no longer works.

Comment (benjamin051000) [reply src/retrieve_data.rs]: image

It's rendering the grass, but nothing on top of it.

Comment (benjamin051000) [reply src/retrieve_data.rs]: Okay, it looks like the issue was the order I was constructing... see https://github.com/louis-e/arnis/compare/f705619aab218cadc7e370c663f5f95f7117a147..cbf8c53312e2846e08e945d905ee906b9fd46ac4 for details. I think it's fixed!

**Comment by benjamin051000** [comment]
This may or may not work with the GUI. I don't know, because I don't build or test the GUI. Soooo yeah, do with that knowledge what you will.

**Comment by louis-e** [comment]
My bbox code was a mess hahha! It doesn't run in GUI mode yet, but I'll take care of that and merge it!

**Comment by louis-e** [comment]
Alright, it's 3:30am now - let me know if this looks good to you or if I messed something up in your code! :D

**Comment by XianlinSheng** [comment]
Does it sound good to represent the position data in two spaces: one real world system (in maybe 'spherical.rs' using LLPoint(the GeoCoord here) and LLBBox (the BBox here)), and a transformed mc system (in cartesian.rs currently, using XZPoint and XZBBox). This will make coordinate transformation much flexible and clearer. I just created the XZBBox struct and based the world editor on XZPoint, XZBBox, so it does not have to generate at (0,0), and I reserved the possibility to extend for more complex bbox shapes.

**Comment by louis-e** [comment]
That sounds interesting, thanks for your idea. Can we merge this PR and follow up with your suggestion in https://github.com/louis-e/arnis/pull/409/ or a seperate PR? It would be cool to cover https://github.com/louis-e/arnis/issues/29 with this and enable multiple generations in a single world, since we can also programmatically set the player spawn point.

**Comment by XianlinSheng** [comment]
Sure. You can merge this PR first and I will keep my #409 updated. These two are the components in a bigger architecture, and I will try to make them work seamlessly.

File: src/bbox.rs [hunk 5]
```diff
@@ -25,13 +25,22 @@ impl BBox {
...
+        
+        // Parse the four floating point values
+        let mut values = [0.0; 4];
+        for (i, part) in parts.iter().enumerate() {
+            values[i] = part.parse::<f64>().map_err(|e| {
+                format!("Failed to parse coordinate value '{}': {}", part, e)
+            })?;
+        }
+        
+        let [min_lat, min_lng, max_lat, max_lng] = values;
```
Comment (benjamin051000) [inline src/bbox.rs]: I'd like to go back to the old logic if possible. 

Can we just do one of these:
-  ~~`.split([',', ' '])` for both chars (but do we really need to support both space and comma-delim values? Maybe we should just pass the delimiter into the constructor here.~~ I see that 1d31dfe fixed this
- IIRC `.try_into()` will supply a good-enough error that it was unable to convert into an array of 4 floats.
- The new float-parsing logic adds several lines.

File: src/bbox.rs [hunk 6]
```diff
@@ -70,6 +79,21 @@ mod tests {
 
         assert_eq!(bbox_result.unwrap(), arnis_correct);
     }
+    
+    #[test]
+    fn test_from_str_spaces() {
```
Comment (benjamin051000) [inline src/bbox.rs:80]: If we _need_ space-delimited strings for GUI purposes, that's fine, but it would be ideal if the CLI and GUI used the same convention.

File: src/bbox.rs [hunk 7]
```diff
@@ -43,8 +43,8 @@ impl BBox {
                 .map_err(|e| format!("Failed to parse coordinate value '{}': {}", part, e))?;
         }
 
-        let [min_lat, min_lng, max_lat, max_lng] = values;
-        Self::new(min_lat, min_lng, max_lat, max_lng)
+        let [min_lng, min_lat, max_lng, max_lat] = values;
+        Self::new(min_lng, min_lat, max_lng, max_lat)
```
Comment (benjamin051000) [inline src/bbox.rs]: Hmm, I thought I had this right. What caused the need to change this? I definitely could have been wrong before, but we should make sure we understand what the ground truth is and probably write it down somewhere so there isn't any more confusion 😅

**Review by benjamin051000 — COMMENTED** [review]
I'm not able to request changes against my own PR, interesting. Well this is what I'm seeing. 

My understanding is that we want this merged soon. I think I'll reset back to the first commit, rebase off main, and then reapply relevant changes to resolve the issues I have with the code changes.

File: gui-src/js/main.js [hunk 8]
```diff
@@ -313,8 +313,8 @@ function handleBboxInput() {
               lat2 >= -90 && lat2 <= 90 &&
               lng2 >= -180 && lng2 <= 180
           ) {
-              // Input is valid; trigger the event
-              const bboxText = `${lat1} ${lng1} ${lat2} ${lng2}`;
+              // Input is valid; trigger the event with consistent comma-separated format
+              const bboxText = `${lat1},${lng1},${lat2},${lng2}`;
```
Comment (benjamin051000) [inline gui-src/js/main.js:317]: If we do this, then we shouldn't need space-delimited strings in the Bbox constructor, right?

**Comment by benjamin051000** [comment]
Made some updates. Moving back to draft until it's working again

File: src/bbox.rs (hunk 1 above)
Comment (benjamin051000) [reply src/bbox.rs:30]: nah, if it fails we will certainly not be able to move on. Just panic now

File: src/bbox.rs (hunk 2 above)
Comment (benjamin051000) [reply src/bbox.rs:33]: no just panic

File: src/bbox.rs (hunk 6 above)
Comment (benjamin051000) [reply src/bbox.rs:80]: Right now it does both. I'll bring back this unit test

**Comment by benjamin051000** [comment]
@louis-e ready for review, please see the comments I wrote

**Comment by louis-e** [comment]
Thanks a lot for your work, looks good to me!! :)
