### PR TITLE
fix chunk file in wrong location

### LINKED ISSUE #53: [BUG] Chunk file at [<X>, <Y>] is in the wrong location; relocating. (Expected [<X>, <Y>], got [<X-96>, <Y-96>])
**Describe the bug**
Immediately after generating the world I get a lot of "Failed to load chunk" messages. The log file gives me the details from the title.

**Used bbox parameter**
```
python3 arnis.py --bbox="-122.078576,37.039181,-122.051110,37.056033" --path ~/.minecraft/saves/Felton
```

**Screenshots**
Will attach log files

**Additional context**
Using Java Minecraft 1.21.1. This is in a brand-new world generated with these parameters (Classic Flat):

```
minecraft:bedrock,2*minecraft:dirt,minecraft:grass_block;minecraft:plains
```

### PR DESCRIPTION
**Pull request by scd31**
WIP as I need to clean up the code and fix the progress bar. It's my bed time, I'll try to get that done tomorrow.

There were two separate problems here.

1. We weren't setting the xPos/zPos chunk data, so the chunks were in the wrong positions.
1. We were only saving modified chunks from the reference MCA file, however we need to save them all (so that we can update all the positions)

Fixes #53 and #38

### CODE REVIEW

File: src/world_editor.rs [hunk 1]
```diff
@@ -220,45 +253,51 @@ impl<'a> WorldEditor<'a> {
...
             ProgressStyle::default_bar()
                 .template(
-                    "{spinner:.green} [{elapsed_precise}] [{bar:45}] {pos}/{len} chunks ({eta})",
+                    "{spinner:.green} [{elapsed_precise}] [{bar:45}] {pos}/{len} regions ({eta})",
                 )
                 .unwrap()
                 .progress_chars("█▓░"),
         );
 
-        let mut chunks_to_process = self.chunks_to_modify.clone(); // Clone to prevent modifying while iterating
```
Comment (scd31) [inline src/world_editor.rs:235]: Getting rid of this clone cut RAM usage roughly in half (:

**Comment by louis-e** [comment]
Thank you for your amazing contributions. This PR, along with your others, is laying a great foundation for future enhancements and improvements!

**Comment by scd31** [comment]
Happy to help! It's a super cool project to work on!
